### ISSUE TITLE
SQL Provider

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/Fig#17]
Provider that uses a relation database source,

**Comment by Venom0us** [comment]
Any ideas on how to tackle this issue if it's still relevant?

**Comment by rofr** [comment]
> Any ideas on how to tackle this issue if it's still relevant?

Yes, I think there could be use cases but no one has actually requested the feature, it was just an idea I added.

1. Add a new project of type class library, Fig.SqlSettings
2. Add a reference to Fig.Core
3. Add a class that derives from SettingsSource, ie SqlSettingsSource
4. Override IEnumerable<(string,string)> GetSettings()

For the implementation I would use some kind of sql provider independent approach with IDbConnection, IDbCommand etc so that any .NET ADO.NET client can be used. Hopefully these types or the equivalent are available in .NET Standard.

If the user provides an SQL Query that retrieves keys and values as strings, then they can have control over the schema. We just execute the query and assume first column is the key and second column is the string value.

So the constructor should take an SQL query, a connection string and a provider.

Maybe add a test case that uses an embedded in-memory database.

Feel free to have a go!

**Comment by rofr** [comment]
That looks like a great start! How about you create a PR and I review and suggest changes? But I can summarize here as well:
* I wouldn't do the actual database reading from within the constructor, it should happen when GetSettings is called.
* I wouldn't pass the connection and command to the constructor, I would pass a connection string and a provider name, create the objects and save them in fields

**Comment by rofr** [comment]
@Venom0us  Here's some info on keeping the sql types generic: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dbproviderfactories

**Comment by Venom0us** [comment]
Can be closed I think, forgot to tag this issue as fixed in pull request I guess.

**Comment by rofr** [comment]
https://www.nuget.org/packages/Fig.SqlSettings/
