### ISSUE TITLE
Where should we hang out?

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/Fig#32]
Our team is now bigger than ever :) Where should we hang out and chat? Slack? gitter? whatsapp?

**Comment by myty** [comment]
I vote gitter but would also be ok with Slack.

**Comment by rofr** [comment]
I started to create a room on gitter but then thought maybe we should transfer the repo to an organisation instead of using my personal GH account. I have 2 orgs we can use, Devrex Labs and Memstate. Devrex Labs is the host of OrigoDB, an in-memory "database" for .NET Framework and memstate, a similar in-memory database for .NET Core. See: 
http://origodb.com/
https://github.com/devrexlabs/origodb
https://github.com/devrexlabs/memstate

I'd like to use Fig with both of these projects and so moving to the Devrex Labs repo seems natural.
Tagging @Venom0us

**Comment by myty** [comment]
> moving to the Devrex Labs repo seems natural
 👍Sounds good to me.

**Comment by rofr** [comment]
Transferred after a majority vote!

**Comment by Venom0us** [comment]
Gitter sounds fine, I usually hang out on discord channels

**Comment by rofr** [comment]
See you all on https://gitter.im/DevrexLabs/Fig then!
